package config

const (
	BATCH_SIZE_DATABASE = 1_000
	BATCH_SIZE_CACHE    = 10_000
	CENTROID_SIZE       = 10_000

	SAMPLE_SIZE             = 5 * BATCH_SIZE_CACHE
	SPLIT_SIZE              = 5
	SUPERSET_MUL            = 5
	KMEANS_ITTERATION_LIMIT = 1_000
)
